# Generated by Django 3.2.13 on 2022-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_retirement', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='date_of_retirement',
        ),
    ]
